package dataModel;

public enum  UserNewHbase {
    address,
    city,
    province,
    country,
    email,
    contact_name,
    group,
    last_message,
    last_message_id,
    last_name,
    uid,
    emails,
    contact_count,
    platform_new,
    names,
    message_count,
    gender,
    last_message_time,
    word_list,
    ana,
    phone,
    msg_words,
    be_contact_count,
    org_words,
    birth,
    card,
    profession,
    msg_updatetime,
    contact_updatetime,
}
